name: Node CI

on: [push, pull_request]

env:
  CI: 'true'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm ci
          npm run test:cov

      - name: Coverage
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: 'true'
  # coverage_complete:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - test
  #   steps:
  #     - name: Coverage complete
  #       uses: coverallsapp/github-action@v1.0.1
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         parallel-finished: "true"
